### ISSUE TITLE
Give support for buildings using custom resources

### ISSUE THREAD

**Issue by MNoya** [Myll/Dota-2-Building-Helper#13]
Could be read either from the npc_units_custom definition or just from an AbilitySpecial, to also display a custom cost tooltip later.

**Comment by Myll** [comment]
Good idea. i can it put a KV like "Resource_Lumber" "20" next to "AbilityGoldCost". Then BH would parse this as a resource and check for player.lumber. You would be responsible for updating player.lumber accordingly throughout the game. 

Only issue with this KV style i'm doing is it'll be hard to handle dynamic changing values (like regular dota KVs).

**Comment by Myll** [comment]
mostly implemented. but see #15 and #16 for current issues surrounding this.
