### ISSUE TITLE
Problems with Scaling

### ISSUE THREAD

**Issue by MNoya** [Myll/Dota-2-Building-Helper#22]
1. Using `"MaxScale"` on the BuildingHelper ability info, the unit will continue scaling even after the construction is complete. The BuildTime and the scaling from 0 to MaxScale should go together.

2. npc_units_custom already has information about the scale of the unit in the form of the "ModelScale" KV. I think it would be better to remove the MaxScale value from the ability definition in favor of the reading the original "ModelScale" of the UnitName. Or at least, make MaxScale optional so that MaxScale can override the ModelScale, but if no max scale is defined, the default unit_custom value will be used (right now it defaults to 1)

3. This might be hard to fix, but ghost particle doesn't show the final scaled size in neither of the unit or ability definitions.

**Comment by Myll** [comment]
fixed 3

**Comment by MNoya** [comment]
fixed 2
