### ISSUE TITLE
how does physics work? and what do all the grid tables to store the information of the grid position info?

### ISSUE THREAD

**Issue by AeroHand** [Myll/Dota-2-Building-Helper#33]
as title

**Comment by Myll** [comment]
> how does physics work?

what do you mean by this? how the ghost particles move?

> what do all the grid tables to store the information of the grid position info?

there are 2 grid tables, GRIDNAV_SQUARES = {}, and BUILDING_SQUARES = {}. the keys in these tables are vectors (converted to a string using VectorString function) of the center points of squares. the values are set to true to indicate the square is closed.

**Comment by AeroHand** [comment]
sry for the confusing question.
in building helper.lua there is

if GridNav:IsBlocked(Vector(x,y,0)) or not GridNav:IsTraversable(Vector(x,y,0)) then

and im very curious about how u judge if the place is blocked or traversable

**Comment by AeroHand** [comment]
also why do u use two grid tables? since one seems to be enough

**Comment by Myll** [comment]
`if GridNav:IsBlocked(Vector(x,y,0)) or not GridNav:IsTraversable(Vector(x,y,0)) then` these two functions are from the API.. i think IsTraversable is influenced by the terrain in hammer, and IsBlocked is just straight up whether the square is blocked by the gridnav. I'm not completely sure though.

i just think it's important to separate between gridnav squares vs regular building squares, so that's why there's 2 tables.

**Comment by AeroHand** [comment]
ok. and the phantom square some times appear to be error when deal with several levels of terrain, (with different z) it sometimes wont back to be plain after the cursor had reached one cliff and then leave. any clue for this?

**Comment by Myll** [comment]
are u using square_sprite or square_projected? can you post a screenshot pls?

**Comment by AeroHand** [comment]
i am using the ur default tinker tower.
some mosaics terrain also affect the square.
my pc is not available now i will giff a screenshot asap

**Comment by AeroHand** [comment]
![qq 20150318022727](https://cloud.githubusercontent.com/assets/6943889/6704427/5d49e8f6-cd16-11e4-9b92-1432c5cebcc5.png)
i tried several times again and that problem seems to be disappear
but for some terrain (with mosaic bricks texture on the ground) the phantom squares seems to be overlapped a little bit
