### ISSUE TITLE
one weird bug

### ISSUE THREAD

**Issue by AeroHand** [Myll/Dota-2-Building-Helper#36]
im trying to merge building helper with my original build system for legion td (i have written it with food, lumber and i used the first version of buildinghelper for its grid) and i met one weird bug

not sure if its my fault. this also happened to ur default sample towers. after casting the building ability, and everything is fine including the phantom, but when i finish planting the building nothing appear. and no error infomation in console too. after doing this several times there's a error info
![12](https://cloud.githubusercontent.com/assets/6943889/6747410/f773dd1a-cea6-11e4-99f8-e57016112dee.jpg)
i have tested in my samplerts its pretty fine. but in my legiontd addon this happens. any clue about that?

**Comment by Myll** [comment]
did you include all these keys in the building ability?

```
		// BuildingHelper info
		"Building"						"1" //bool
		"BuildingSize"					"3" // this is (3x64) by (3x64) units, so 9 squares.
		"BuildTime"						"2.0"
		"AbilityCastRange"				"100"
		"UpdateHealth"					"1" //bool
		"Scale"							"1" //bool
		"MaxScale"						"1.3"
		"PlayerCanControl"				"1" //bool. Should the player issuing this build command be able to control the building once built?
		//"CancelsBuildingGhost"			"0" //bool
		// Note: if unit uses a npc_dota_hero baseclass, you must use the npc_dota_hero name.
		"UnitName"						"npc_dota_hero_enigma"
		"AbilityCooldown"				"0"
		"AbilityGoldCost"				"10"
		// End of BuildingHelper info
```

**Comment by AeroHand** [comment]
yes. this error also occurs to ur default towers. im wondering if i have missed some files or deleted sth in the wrong way.
